learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("learning_logs.urls")),
    path("users/", include("users.urls")),
]

learning_log/learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = "learning_logs"  # namespace
urlpatterns = [
    # Home page
    path("", views.index, name="index"),
    path("topics/", views.topics, name="topics"),
    # Define page for a single topic.
    path("topics/<int:topic_id>/", views.topic, name="topic"),
    # Page for adding new topic
    path("new_topic/", views.new_topic, name="new_topic"),
    # Page for adding a new entry
    path("new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),
    # Path for editing an entry
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),
]

learning_log/users/urls.py
"""Define URL patterns for users."""


from django.urls import path, include

from . import views

app_name = "users"
urlpatterns = [
    # Include default auth urls.
    path("", include("django.contrib.auth.urls")),
    # Registration page.
    path("register/", views.register, name="register"),
]

learning_log/learning_logs/models.py
"""Define the data we want to manage in our app."""
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# A model tells Django how to work with data that will be stored in the app.


class Topic(models.Model):
    """A topic that user is learning about."""

    text = models.CharField(max_length=200)  # topic name
    date_added = models.DateTimeField(auto_now_add=True)
    # (auto_now_add=True) -> sets to current date and time whenever the user creates a new topic
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    # we add owner field to Topic, which establishes a foreign key relationship to the User model
    # If a user is deleted, all the topics associated with that user will be deleted as well.

    def __str__(self):
        """Return the string respresentation of the model."""
        return str(self.text)


class Entry(models.Model):
    """Something specific learned about a topic."""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        """Return a string representation of a model."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        return f"{self.text}"

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    """A topic form in django style."""

    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    """An entry for a specific topic."""

    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

learning_log/learning_logs/views.py
from django import http
from django.http import Http404
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    """The home page for Learning Log."""
    return render(request, "learning_logs/index.html")


@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by(
        "date_added"
    )  # Topic.objects.order_by("date_added")
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    # if topic.owner != request.user:
    #     raise Http404
    check_topic_owner(topic, request)  # refactor
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)


@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != "POST":
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # form.save()
            return redirect("learning_logs:topics")
    # Display a blank or invalid form
    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != "POST":
        form = EntryForm()
    else:
        # POST data submitted; process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)  # commit=False does not save in db
            new_entry.topic = topic  # asspciate with correct db
            new_entry.save()  # now save in db
            return redirect("learning_logs:topic", topic_id=topic_id)

    # Display a blank or invalid form
    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/new_entry.html", context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(topic, request)  # refactor
    # if topic.owner != request.user:
    #     raise Http404

    if request.method != "POST":
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("learning_logs:topic", topic_id=topic.id)
    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, "learning_logs/edit_entry.html", context)


def check_topic_owner(topic, request):
    """Checks if the current user is the owner of the topic."""
    if topic.owner != request.user:
        raise Http404

learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user."""
    if request.method != "POST":
        # Display blank form
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()

            # Log the user inn and then redirect to home page
            login(request, new_user)
            return redirect("learning_logs:index")
    # Display a blank or invalid form.
    context = {"form": form}
    return render(request, "registration/register.html", context)

learning_log/learning_logs/templates/learning_logs/base.html
<p>
	<a href="{% url 'learning_logs:index' %}">Learning Log</a> -
	<a href="{% url 'learning_logs:topics' %}">Topics</a> - 
	{% if user.is_authenticated %} 
		<p>Hello, {{user.username}}.</p>
		<a href="{% url 'users:logout' %}">Log out</a>
	{% else %}
		<a href="{% url 'users:register' %}">Register</a> -
		<a href="{% url 'users:login' %}">Log in</a>
	{% endif %}
</p>

{% block content %}{% endblock content %}

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{%extends "learning_logs/base.html"%} {% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

<p>Edit entry:</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
	{% csrf_token %} {{form.as_p}}
	<button name="submit">Save changes</button>
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{%extends "learning_logs/base.html"%} {% block content %}
<p>
	Learning Log helps you keep track of your learning, for any topic you're
	learning about.
</p>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %} {%block content%}

<p><a href="{url 'learning_logs:topic' topic.id}">{{topic}}</a></p>

<p>Add a new entry:</p>
<form action="{%url 'learning_logs:new_entry' topic.id%}" method="post">
	{%csrf_token%} {{form.as_p}}
	<button name="submit">Add entry</button>
</form>

{%endblock content%}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %} {%block content%}

<p>Add a new topic:</p>

<form action="{%url 'learning_logs:new_topic'%}" method="post">
	{%csrf_token%} {{form.as_p}}
	<button name="submit">Add topic</button>
</form>

{%endblock content%}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %} {% block content %}

<p>Topic: {{topic}}</p>

<p>Entries:</p>
<p>
	<a href="{%url 'learning_logs:new_entry' topic.id%}">Add new entry</a>
</p>
<ul>
	{% for entry in entries %}
	<li>
		<p>{{entry.date_added|date:'M d, Y H:i'}}</p>
		<p>{{entry.text|linebreaks}}</p>
		<p>
			<a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
		</p>
	</li>
	{% empty %}
	<p>There are no entries for this topic yet.</p>
	{% endfor %}
</ul>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %} {% block content %}

<p>Topics</p>

<ul>
	{%for topic in topics%}
	<li>
		<a href="{% url 'learning_logs:topic' topic.id%}">{{topic}}</a>
	</li>
	{%empty%}
	<li>No topics have been added yet.</li>
	{%endfor%}
</ul>
<a href="{%url 'learning_logs:new_topic'%}">Add a new topic</a>
{% endblock %}